ipv6_neighbor:
  static_entries:
    - ipv6_address: 11:22:33:44:55:66:77:88
      interface: Ethernet1
      mac_address: 11.22.33
      vrf: MGMT
    - ipv6_address: ::ffff:192.1.56.10
      interface: Loopback99
      mac_address: aaaf.1234.bcbf
  cache: True
  persistent: True
  refresh_delay: 1000
