---
traffic_policies:
  options:
    counter_per_interface: true
  field_sets:
    ports:
      - name: SERVICE-DEMO
        port_range: "10,20,80,440-450"
    ipv4:
      - name: DEMO-01
        prefixes:
          - 10.0.0.0/8
          - 192.168.0.0/16
      - name: DEMO-02
        prefixes:
          - 172.16.0.0/12
          - 224.0.0.0/8
  policies:
    - name: BLUE-C1-POLICY
      default_actions:
        ipv4:
          drop: true
      matches:
        - name: POLICY-WITHOUT-SOURCE
          type: ipv4
          protocols:
            - protocol: neighbors
            - protocol: ip
            - protocol: udp
              dst_port: "1,10-20"
            # - protocol: tcp
            #   dst_field: SERVICE-DEMO
              
            - protocol: tcp
              src_port: "22"
              flags:
                - initial
              icmp_type:
                - echo
                - echo-reply
            - protocol: icmp
              src_field: SERVICE-DEMO
              flags:
                - initial
              
          actions:
            log: false
        - name: POLICY-WITH-DEST-PREFIX
          type: ipv4
          destination:
            prefixes:
              - 10.0.0.0/8
              - 192.168.0.0/16
        - name: POLICY-WITH-DEST-PREFIX-AND-LIST
          type: ipv4
          destination:
            prefixes:
              - 10.0.0.0/8
              - 192.168.0.0/16
            prefix_lists:
              - DEMO-01
          protocols:
            - protocol: udp
              dst_port: "1,10-20"
              flags:
                - initial
            - protocol: tcp
              dst_field: SERVICE-DEMO
        - name: BLUE-C1-POLICY-01
          type: ipv4
          source:
            prefixes:
              - 10.0.0.0/8
              - 192.168.0.0/16
          destination:
            prefix_lists:
              - DEMO-01
          protocols:
            - protocol: tcp
              src_port: "1,10-20"
            - protocol: udp
              src_field: SERVICE-DEMO
              flags:
                - initial
          ttl: "10, 20-30"
          actions:
            traffic_class: 5
        - name: BLUE-C1-POLICY-02
          type: ipv4
          source:
            prefix_lists:
              - DEMO-01
              - DEMO-02
          protocols:
            - protocol: tcp
              dst_field: SERVICE-DEMO
              flags:
                - established
            - protocol: icmp
          actions:
            count: DEMO-TRAFFIC
            dscp: 60
        - name: BLUE-C1-POLICY-03
          type: ipv4
          source:
            prefix_lists:
              - DEMO-01
          protocols:
            - protocol: icmp
              icmp_type:
                - echo
                - echo-reply
          fragment:
            offset: "1124, 2000-2010"
          actions:
            count: DROP-PACKETS
            drop: true
            log: true
        - name: BLUE-C1-POLICY-04
          type: ipv4
          source:
            prefix_lists:
              - DEMO-02
          destination:
            prefix_lists:
              - DEMO-01
          protocols:
            - protocol: tcp
              src_port: "22"
              flags:
                - established
            - protocol: icmp
          actions:
            traffic_class: 5
        - name: BLUE-C1-POLICY-05
          type: ipv4
          source:
            prefix_lists:
              - DEMO-02
          destination:
            prefix_lists:
              - DEMO-01
          protocols:
            - protocol: tcp
          fragment:
          actions:
            traffic_class: 5
    - name: BLUE-C2-POLICY
      default_actions:
        ipv4:
          drop: true
          log: true
      matches:
        - name: BLUE-C2-POLICY-01
          type: ipv4
          source:
            prefixes:
              - 10.0.0.0/8
              - 192.168.0.0/16
          protocols:
            - protocol: tcp
              src_port: "1,10-20"
            - protocol: icmp
          actions:
            traffic_class: 5
        - name: BLUE-C2-POLICY-02
          type: ipv4
          source:
            prefix_lists:
              - DEMO-01
              - DEMO-02
          protocols:
            - protocol: tcp
              src_field: SERVICE-DEMO
            - protocol: icmp
          actions:
            count: DEMO-TRAFFIC
            dscp: 60
        - name: BLUE-C2-POLICY-03
          type: ipv4
          source:
            prefix_lists:
              - DEMO-01
          protocols:
            - protocol: tcp
          actions:
            drop: true
    - name: BLUE-C3-POLICY
      default_actions:
        ipv4:
          count: test
          traffic_class: 10
          dscp: 11
ethernet_interfaces:
  - name: Ethernet1
    type: routed
    traffic_policy:
      input: BLUE-C1-POLICY
      output: BLUE-C2-POLICY

port_channel_interfaces:
  - name: Port-Channel2
    type: routed
    traffic_policy:
      input: BLUE-C1-POLICY
      output: BLUE-C2-POLICY
