### VLAN Interfaces ###

# Testing vlan_interfaces as dict of dict
# Dict type is deprecated in 4.0.0. To be removed in 5.0.0
vlan_interfaces:
  Vlan1:
    description: test ipv6_address_virtual
    ipv6_enable: true

  Vlan2:
    description: test ipv6_address_virtual and ipv6_address_virtuals
    ipv6_enable: true
    ipv6_address: 1b11:3a00:22b0:5200::15/64
    ipv6_nd_managed_config_flag: true
    # Testing ipv6_nd_prefixes as dict of dict
    # Dict type is deprecated in 4.0.0. To be removed in 5.0.0
    ipv6_nd_prefixes:
      1b11:3a00:22b0:5200::/64:
        valid_lifetime: infinite
        preferred_lifetime: infinite
        no_autoconfig_flag: true

  Vlan3:
    description: test ipv6_address_virtual
    ipv6_enable: true
    ipv6_address: 1b11:3a00:22b3:5200::15/64

  Vlan42:
    description: SVI Description
    shutdown: false
    # Testing ip_helpers as dict of dict
    # Dict type is deprecated in 4.0.0. To be removed in 5.0.0
    ip_helpers:
      10.10.96.151:
        source_interface: Loopback0
      10.10.96.150:
        source_interface: Loopback0
      10.10.64.150:
        source_interface: Loopback0
