## AAA Accounting
aaa_accounting:
  exec:
    console:
      type: start-stop
      group: TACACS
      logging: true
    default:
      type: start-stop
      group: TACACS
      logging: true
  system:
    default:
      type: start-stop
      group: TACACS
  dot1x:
    default:
      type: start-stop
      group: RADIUS
  commands:
    console:
      - commands: all
        type: start-stop
        group: TACACS
        logging: true
      - commands: 0
        type: start-stop
        logging: true
    default:
      - commands: all
        type: start-stop
        group: TACACS
        logging: true
      - commands: 0
        type: start-stop
        logging: true
