### AAA Server Groups
aaa_server_groups:
  - name: TACACS1
    type: tacacs+
    servers:
      - server: 10.10.10.157
        vrf: mgt
      - server: 10.10.10.249
  - name: TACACS2
    type: tacacs+
    servers:
      - server: 192.168.10.157
        vrf: mgt
      - server: 10.10.10.248
