---

wan_mode: cv-pathfinder

cv_pathfinder_regions:
  - name: Global
    id: 1
    sites:
      - name: DC1
        id: 100

wan_ipsec_profiles:
  control_plane:
    shared_key: 0110100A480E0A0E231D1E
  data_plane:
    shared_key: 0110100A480E0A0E231D1E
